name: 'Build and Deploy'
  
on:
  workflow_dispatch:
  push:
    branches: main
  
jobs:
  Release-Build-and-Deploy: 
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: microsoft/setup-msbuild@v1.3.1
    
    - name: 1. Versioning Release
      uses: CalvinAllen/action-vs-vsix-versioner@v1
      with:
        extension-manifest-file: './src/CodingWithCalvin.VSKraken/source.extension.vsixmanifest'
        extension-source-file: './src/CodingWithCalvin.VSKraken/source.extension.cs'

    - name: 2. Bootstrapping NuGet Installer
      uses: nuget/setup-nuget@v1.1.1
    
    - name: 3. Restoring Packages
      run: nuget restore ./src/CodingWithCalvin.VSKraken.sln
    
    - name: 4. Building x64 Project
      run: msbuild './src/CodingWithCalvin.VSKraken/CodingWithCalvin.VSKraken.csproj' /p:configuration='Release' /p:platform='x64'

    - name: 5. Publishing x64 Build Artifact
      uses: actions/upload-artifact@v3
      with:
        path: '${{ github.workspace }}\src\CodingWithCalvin.VSKraken\bin\x64\Release\CodingWithCalvin.VSKraken.vsix'
        name: latest-x64
